---
  aa_secondary_cluster:
    hosts:
      aa_secondary_cluster_n1:
        ansible_host: "{{ internal_ip }}"
        ansible_become_pass: "{{ ansible_become_password }}"
      aa_secondary_cluster_n2:
        ansible_host: "{{ internal_ip }}"
        ansible_become_pass: "{{ ansible_become_password }}"
      aa_secondary_cluster_n3:
        ansible_host: "{{ internal_ip }}"
        ansible_become_pass: "{{ ansible_become_password }}"
